name: my_package
description: "A simple and lightweight Flutter package offering reusable utilities for Flutter applications."

version: 0.0.1

homepage: https://github.com/busttech/my_package
repository: https://github.com/busttech/my_package
issue_tracker: https://github.com/busttech/my_package/issues

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=1.17.0"


dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  # assets:
  #   - images/a_dot_burr.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
