name: busttech_photo_overlay
description: "A lightweight Flutter overlay toolkit to add logos, stickers, frames and text on images. Optimized for high-resolution exports and simple API."
version: 0.0.1
homepage: https://github.com/busttech/busttech_photo_overlay
repository: https://github.com/busttech/busttech_photo_overlay
issue_tracker: https://github.com/busttech/busttech_photo_overlay/issues

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.0
  image: ^4.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/stickers/